// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: integration_credentials.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIntegrationCredential = `-- name: CreateIntegrationCredential :one
INSERT INTO integration_credentials (
    id, integration_id, user_id,
    credential_type, access_token, refresh_token, token_expires_at, scopes,
    is_primary,
    created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, now(), now())
RETURNING id, integration_id, user_id, credential_type, access_token, refresh_token, token_expires_at, scopes, is_primary, created_at, updated_at, revoked_at
`

type CreateIntegrationCredentialParams struct {
	ID             int64              `json:"id"`
	IntegrationID  int64              `json:"integration_id"`
	UserID         *int64             `json:"user_id"`
	CredentialType string             `json:"credential_type"`
	AccessToken    string             `json:"access_token"`
	RefreshToken   *string            `json:"refresh_token"`
	TokenExpiresAt pgtype.Timestamptz `json:"token_expires_at"`
	Scopes         []string           `json:"scopes"`
	IsPrimary      bool               `json:"is_primary"`
}

func (q *Queries) CreateIntegrationCredential(ctx context.Context, arg CreateIntegrationCredentialParams) (IntegrationCredential, error) {
	row := q.db.QueryRow(ctx, createIntegrationCredential,
		arg.ID,
		arg.IntegrationID,
		arg.UserID,
		arg.CredentialType,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiresAt,
		arg.Scopes,
		arg.IsPrimary,
	)
	var i IntegrationCredential
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.UserID,
		&i.CredentialType,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.Scopes,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const deleteIntegrationCredential = `-- name: DeleteIntegrationCredential :exec
DELETE FROM integration_credentials WHERE id = $1
`

func (q *Queries) DeleteIntegrationCredential(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteIntegrationCredential, id)
	return err
}

const getCredentialByIntegrationAndUser = `-- name: GetCredentialByIntegrationAndUser :one
SELECT id, integration_id, user_id, credential_type, access_token, refresh_token, token_expires_at, scopes, is_primary, created_at, updated_at, revoked_at FROM integration_credentials
WHERE integration_id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type GetCredentialByIntegrationAndUserParams struct {
	IntegrationID int64  `json:"integration_id"`
	UserID        *int64 `json:"user_id"`
}

func (q *Queries) GetCredentialByIntegrationAndUser(ctx context.Context, arg GetCredentialByIntegrationAndUserParams) (IntegrationCredential, error) {
	row := q.db.QueryRow(ctx, getCredentialByIntegrationAndUser, arg.IntegrationID, arg.UserID)
	var i IntegrationCredential
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.UserID,
		&i.CredentialType,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.Scopes,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getIntegrationCredential = `-- name: GetIntegrationCredential :one
SELECT id, integration_id, user_id, credential_type, access_token, refresh_token, token_expires_at, scopes, is_primary, created_at, updated_at, revoked_at FROM integration_credentials WHERE id = $1
`

func (q *Queries) GetIntegrationCredential(ctx context.Context, id int64) (IntegrationCredential, error) {
	row := q.db.QueryRow(ctx, getIntegrationCredential, id)
	var i IntegrationCredential
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.UserID,
		&i.CredentialType,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.Scopes,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getPrimaryCredentialByIntegration = `-- name: GetPrimaryCredentialByIntegration :one
SELECT id, integration_id, user_id, credential_type, access_token, refresh_token, token_expires_at, scopes, is_primary, created_at, updated_at, revoked_at FROM integration_credentials
WHERE integration_id = $1 AND is_primary = true AND revoked_at IS NULL
`

func (q *Queries) GetPrimaryCredentialByIntegration(ctx context.Context, integrationID int64) (IntegrationCredential, error) {
	row := q.db.QueryRow(ctx, getPrimaryCredentialByIntegration, integrationID)
	var i IntegrationCredential
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.UserID,
		&i.CredentialType,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.Scopes,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listActiveCredentialsByIntegration = `-- name: ListActiveCredentialsByIntegration :many
SELECT id, integration_id, user_id, credential_type, access_token, refresh_token, token_expires_at, scopes, is_primary, created_at, updated_at, revoked_at FROM integration_credentials
WHERE integration_id = $1 AND revoked_at IS NULL
ORDER BY is_primary DESC, created_at DESC
`

func (q *Queries) ListActiveCredentialsByIntegration(ctx context.Context, integrationID int64) ([]IntegrationCredential, error) {
	rows, err := q.db.Query(ctx, listActiveCredentialsByIntegration, integrationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IntegrationCredential
	for rows.Next() {
		var i IntegrationCredential
		if err := rows.Scan(
			&i.ID,
			&i.IntegrationID,
			&i.UserID,
			&i.CredentialType,
			&i.AccessToken,
			&i.RefreshToken,
			&i.TokenExpiresAt,
			&i.Scopes,
			&i.IsPrimary,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCredentialsByIntegration = `-- name: ListCredentialsByIntegration :many
SELECT id, integration_id, user_id, credential_type, access_token, refresh_token, token_expires_at, scopes, is_primary, created_at, updated_at, revoked_at FROM integration_credentials
WHERE integration_id = $1
ORDER BY is_primary DESC, created_at DESC
`

func (q *Queries) ListCredentialsByIntegration(ctx context.Context, integrationID int64) ([]IntegrationCredential, error) {
	rows, err := q.db.Query(ctx, listCredentialsByIntegration, integrationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IntegrationCredential
	for rows.Next() {
		var i IntegrationCredential
		if err := rows.Scan(
			&i.ID,
			&i.IntegrationID,
			&i.UserID,
			&i.CredentialType,
			&i.AccessToken,
			&i.RefreshToken,
			&i.TokenExpiresAt,
			&i.Scopes,
			&i.IsPrimary,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllCredentialsByIntegration = `-- name: RevokeAllCredentialsByIntegration :exec
UPDATE integration_credentials
SET revoked_at = now(), is_primary = false, updated_at = now()
WHERE integration_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllCredentialsByIntegration(ctx context.Context, integrationID int64) error {
	_, err := q.db.Exec(ctx, revokeAllCredentialsByIntegration, integrationID)
	return err
}

const revokeCredential = `-- name: RevokeCredential :one
UPDATE integration_credentials
SET revoked_at = now(), is_primary = false, updated_at = now()
WHERE id = $1
RETURNING id, integration_id, user_id, credential_type, access_token, refresh_token, token_expires_at, scopes, is_primary, created_at, updated_at, revoked_at
`

func (q *Queries) RevokeCredential(ctx context.Context, id int64) (IntegrationCredential, error) {
	row := q.db.QueryRow(ctx, revokeCredential, id)
	var i IntegrationCredential
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.UserID,
		&i.CredentialType,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.Scopes,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const setCredentialAsPrimary = `-- name: SetCredentialAsPrimary :exec
UPDATE integration_credentials
SET is_primary = (id = $2), updated_at = now()
WHERE integration_id = $1 AND revoked_at IS NULL
`

type SetCredentialAsPrimaryParams struct {
	IntegrationID int64 `json:"integration_id"`
	ID            int64 `json:"id"`
}

func (q *Queries) SetCredentialAsPrimary(ctx context.Context, arg SetCredentialAsPrimaryParams) error {
	_, err := q.db.Exec(ctx, setCredentialAsPrimary, arg.IntegrationID, arg.ID)
	return err
}

const updateCredentialTokens = `-- name: UpdateCredentialTokens :one
UPDATE integration_credentials
SET 
    access_token = $2,
    refresh_token = $3,
    token_expires_at = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, integration_id, user_id, credential_type, access_token, refresh_token, token_expires_at, scopes, is_primary, created_at, updated_at, revoked_at
`

type UpdateCredentialTokensParams struct {
	ID             int64              `json:"id"`
	AccessToken    string             `json:"access_token"`
	RefreshToken   *string            `json:"refresh_token"`
	TokenExpiresAt pgtype.Timestamptz `json:"token_expires_at"`
}

func (q *Queries) UpdateCredentialTokens(ctx context.Context, arg UpdateCredentialTokensParams) (IntegrationCredential, error) {
	row := q.db.QueryRow(ctx, updateCredentialTokens,
		arg.ID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiresAt,
	)
	var i IntegrationCredential
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.UserID,
		&i.CredentialType,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiresAt,
		&i.Scopes,
		&i.IsPrimary,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RevokedAt,
	)
	return i, err
}
