// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: integrations.sql

package sqlc

import (
	"context"
)

const createIntegration = `-- name: CreateIntegration :one
INSERT INTO integrations (
    id, workspace_id, organization_id, connected_by_user_id,
    provider, provider_base_url,
    external_org_id, external_workspace_id,
    created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, now(), now())
RETURNING id, workspace_id, organization_id, connected_by_user_id, provider, provider_base_url, external_org_id, external_workspace_id, created_at, updated_at
`

type CreateIntegrationParams struct {
	ID                  int64   `json:"id"`
	WorkspaceID         int64   `json:"workspace_id"`
	OrganizationID      int64   `json:"organization_id"`
	ConnectedByUserID   int64   `json:"connected_by_user_id"`
	Provider            string  `json:"provider"`
	ProviderBaseUrl     *string `json:"provider_base_url"`
	ExternalOrgID       *string `json:"external_org_id"`
	ExternalWorkspaceID *string `json:"external_workspace_id"`
}

func (q *Queries) CreateIntegration(ctx context.Context, arg CreateIntegrationParams) (Integration, error) {
	row := q.db.QueryRow(ctx, createIntegration,
		arg.ID,
		arg.WorkspaceID,
		arg.OrganizationID,
		arg.ConnectedByUserID,
		arg.Provider,
		arg.ProviderBaseUrl,
		arg.ExternalOrgID,
		arg.ExternalWorkspaceID,
	)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.OrganizationID,
		&i.ConnectedByUserID,
		&i.Provider,
		&i.ProviderBaseUrl,
		&i.ExternalOrgID,
		&i.ExternalWorkspaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIntegration = `-- name: DeleteIntegration :exec
DELETE FROM integrations WHERE id = $1
`

func (q *Queries) DeleteIntegration(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteIntegration, id)
	return err
}

const getIntegration = `-- name: GetIntegration :one
SELECT id, workspace_id, organization_id, connected_by_user_id, provider, provider_base_url, external_org_id, external_workspace_id, created_at, updated_at FROM integrations WHERE id = $1
`

func (q *Queries) GetIntegration(ctx context.Context, id int64) (Integration, error) {
	row := q.db.QueryRow(ctx, getIntegration, id)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.OrganizationID,
		&i.ConnectedByUserID,
		&i.Provider,
		&i.ProviderBaseUrl,
		&i.ExternalOrgID,
		&i.ExternalWorkspaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIntegrationByWorkspaceAndProvider = `-- name: GetIntegrationByWorkspaceAndProvider :one
SELECT id, workspace_id, organization_id, connected_by_user_id, provider, provider_base_url, external_org_id, external_workspace_id, created_at, updated_at FROM integrations 
WHERE workspace_id = $1 AND provider = $2
`

type GetIntegrationByWorkspaceAndProviderParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	Provider    string `json:"provider"`
}

func (q *Queries) GetIntegrationByWorkspaceAndProvider(ctx context.Context, arg GetIntegrationByWorkspaceAndProviderParams) (Integration, error) {
	row := q.db.QueryRow(ctx, getIntegrationByWorkspaceAndProvider, arg.WorkspaceID, arg.Provider)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.OrganizationID,
		&i.ConnectedByUserID,
		&i.Provider,
		&i.ProviderBaseUrl,
		&i.ExternalOrgID,
		&i.ExternalWorkspaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIntegrationsByOrganization = `-- name: ListIntegrationsByOrganization :many
SELECT id, workspace_id, organization_id, connected_by_user_id, provider, provider_base_url, external_org_id, external_workspace_id, created_at, updated_at FROM integrations 
WHERE organization_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListIntegrationsByOrganization(ctx context.Context, organizationID int64) ([]Integration, error) {
	rows, err := q.db.Query(ctx, listIntegrationsByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Integration{}
	for rows.Next() {
		var i Integration
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.OrganizationID,
			&i.ConnectedByUserID,
			&i.Provider,
			&i.ProviderBaseUrl,
			&i.ExternalOrgID,
			&i.ExternalWorkspaceID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntegrationsByWorkspace = `-- name: ListIntegrationsByWorkspace :many
SELECT id, workspace_id, organization_id, connected_by_user_id, provider, provider_base_url, external_org_id, external_workspace_id, created_at, updated_at FROM integrations 
WHERE workspace_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListIntegrationsByWorkspace(ctx context.Context, workspaceID int64) ([]Integration, error) {
	rows, err := q.db.Query(ctx, listIntegrationsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Integration{}
	for rows.Next() {
		var i Integration
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.OrganizationID,
			&i.ConnectedByUserID,
			&i.Provider,
			&i.ProviderBaseUrl,
			&i.ExternalOrgID,
			&i.ExternalWorkspaceID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIntegration = `-- name: UpdateIntegration :one
UPDATE integrations
SET 
    provider_base_url = coalesce($2, provider_base_url),
    external_org_id = coalesce($3, external_org_id),
    external_workspace_id = coalesce($4, external_workspace_id),
    updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, organization_id, connected_by_user_id, provider, provider_base_url, external_org_id, external_workspace_id, created_at, updated_at
`

type UpdateIntegrationParams struct {
	ID                  int64   `json:"id"`
	ProviderBaseUrl     *string `json:"provider_base_url"`
	ExternalOrgID       *string `json:"external_org_id"`
	ExternalWorkspaceID *string `json:"external_workspace_id"`
}

func (q *Queries) UpdateIntegration(ctx context.Context, arg UpdateIntegrationParams) (Integration, error) {
	row := q.db.QueryRow(ctx, updateIntegration,
		arg.ID,
		arg.ProviderBaseUrl,
		arg.ExternalOrgID,
		arg.ExternalWorkspaceID,
	)
	var i Integration
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.OrganizationID,
		&i.ConnectedByUserID,
		&i.Provider,
		&i.ProviderBaseUrl,
		&i.ExternalOrgID,
		&i.ExternalWorkspaceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
