// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: integration_configs.sql

package sqlc

import (
	"context"
	"encoding/json"
)

const createIntegrationConfig = `-- name: CreateIntegrationConfig :one
INSERT INTO integration_configs (
    id, integration_id, key, value, config_type,
    created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, now(), now())
RETURNING id, integration_id, key, value, config_type, created_at, updated_at
`

type CreateIntegrationConfigParams struct {
	ID            int64           `json:"id"`
	IntegrationID int64           `json:"integration_id"`
	Key           string          `json:"key"`
	Value         json.RawMessage `json:"value"`
	ConfigType    string          `json:"config_type"`
}

func (q *Queries) CreateIntegrationConfig(ctx context.Context, arg CreateIntegrationConfigParams) (IntegrationConfig, error) {
	row := q.db.QueryRow(ctx, createIntegrationConfig,
		arg.ID,
		arg.IntegrationID,
		arg.Key,
		arg.Value,
		arg.ConfigType,
	)
	var i IntegrationConfig
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.Key,
		&i.Value,
		&i.ConfigType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIntegrationConfig = `-- name: DeleteIntegrationConfig :exec
DELETE FROM integration_configs WHERE id = $1
`

func (q *Queries) DeleteIntegrationConfig(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteIntegrationConfig, id)
	return err
}

const deleteIntegrationConfigsByIntegration = `-- name: DeleteIntegrationConfigsByIntegration :exec
DELETE FROM integration_configs WHERE integration_id = $1
`

func (q *Queries) DeleteIntegrationConfigsByIntegration(ctx context.Context, integrationID int64) error {
	_, err := q.db.Exec(ctx, deleteIntegrationConfigsByIntegration, integrationID)
	return err
}

const getIntegrationConfig = `-- name: GetIntegrationConfig :one
SELECT id, integration_id, key, value, config_type, created_at, updated_at FROM integration_configs WHERE id = $1
`

func (q *Queries) GetIntegrationConfig(ctx context.Context, id int64) (IntegrationConfig, error) {
	row := q.db.QueryRow(ctx, getIntegrationConfig, id)
	var i IntegrationConfig
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.Key,
		&i.Value,
		&i.ConfigType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIntegrationConfigByKey = `-- name: GetIntegrationConfigByKey :one
SELECT id, integration_id, key, value, config_type, created_at, updated_at FROM integration_configs 
WHERE integration_id = $1 AND key = $2
`

type GetIntegrationConfigByKeyParams struct {
	IntegrationID int64  `json:"integration_id"`
	Key           string `json:"key"`
}

func (q *Queries) GetIntegrationConfigByKey(ctx context.Context, arg GetIntegrationConfigByKeyParams) (IntegrationConfig, error) {
	row := q.db.QueryRow(ctx, getIntegrationConfigByKey, arg.IntegrationID, arg.Key)
	var i IntegrationConfig
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.Key,
		&i.Value,
		&i.ConfigType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIntegrationConfigs = `-- name: ListIntegrationConfigs :many
SELECT id, integration_id, key, value, config_type, created_at, updated_at FROM integration_configs 
WHERE integration_id = $1
ORDER BY key ASC
`

func (q *Queries) ListIntegrationConfigs(ctx context.Context, integrationID int64) ([]IntegrationConfig, error) {
	rows, err := q.db.Query(ctx, listIntegrationConfigs, integrationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IntegrationConfig{}
	for rows.Next() {
		var i IntegrationConfig
		if err := rows.Scan(
			&i.ID,
			&i.IntegrationID,
			&i.Key,
			&i.Value,
			&i.ConfigType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIntegrationConfigsByType = `-- name: ListIntegrationConfigsByType :many
SELECT id, integration_id, key, value, config_type, created_at, updated_at FROM integration_configs 
WHERE integration_id = $1 AND config_type = $2
ORDER BY key ASC
`

type ListIntegrationConfigsByTypeParams struct {
	IntegrationID int64  `json:"integration_id"`
	ConfigType    string `json:"config_type"`
}

func (q *Queries) ListIntegrationConfigsByType(ctx context.Context, arg ListIntegrationConfigsByTypeParams) ([]IntegrationConfig, error) {
	rows, err := q.db.Query(ctx, listIntegrationConfigsByType, arg.IntegrationID, arg.ConfigType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IntegrationConfig{}
	for rows.Next() {
		var i IntegrationConfig
		if err := rows.Scan(
			&i.ID,
			&i.IntegrationID,
			&i.Key,
			&i.Value,
			&i.ConfigType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIntegrationConfig = `-- name: UpdateIntegrationConfig :one
UPDATE integration_configs
SET value = $2, updated_at = now()
WHERE id = $1
RETURNING id, integration_id, key, value, config_type, created_at, updated_at
`

type UpdateIntegrationConfigParams struct {
	ID    int64           `json:"id"`
	Value json.RawMessage `json:"value"`
}

func (q *Queries) UpdateIntegrationConfig(ctx context.Context, arg UpdateIntegrationConfigParams) (IntegrationConfig, error) {
	row := q.db.QueryRow(ctx, updateIntegrationConfig, arg.ID, arg.Value)
	var i IntegrationConfig
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.Key,
		&i.Value,
		&i.ConfigType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertIntegrationConfig = `-- name: UpsertIntegrationConfig :one
INSERT INTO integration_configs (id, integration_id, key, value, config_type, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, now(), now())
ON CONFLICT (id) DO UPDATE
SET value = EXCLUDED.value, updated_at = now()
RETURNING id, integration_id, key, value, config_type, created_at, updated_at
`

type UpsertIntegrationConfigParams struct {
	ID            int64           `json:"id"`
	IntegrationID int64           `json:"integration_id"`
	Key           string          `json:"key"`
	Value         json.RawMessage `json:"value"`
	ConfigType    string          `json:"config_type"`
}

func (q *Queries) UpsertIntegrationConfig(ctx context.Context, arg UpsertIntegrationConfigParams) (IntegrationConfig, error) {
	row := q.db.QueryRow(ctx, upsertIntegrationConfig,
		arg.ID,
		arg.IntegrationID,
		arg.Key,
		arg.Value,
		arg.ConfigType,
	)
	var i IntegrationConfig
	err := row.Scan(
		&i.ID,
		&i.IntegrationID,
		&i.Key,
		&i.Value,
		&i.ConfigType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
