// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invitations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvitation = `-- name: AcceptInvitation :one
UPDATE invitations 
SET status = 'accepted', 
    accepted_by = $2, 
    accepted_at = now()
WHERE id = $1 AND status = 'pending'
RETURNING id, email, token, status, invited_by, accepted_by, expires_at, created_at, accepted_at
`

type AcceptInvitationParams struct {
	ID         int64  `json:"id"`
	AcceptedBy *int64 `json:"accepted_by"`
}

func (q *Queries) AcceptInvitation(ctx context.Context, arg AcceptInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, acceptInvitation, arg.ID, arg.AcceptedBy)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Token,
		&i.Status,
		&i.InvitedBy,
		&i.AcceptedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (id, email, token, status, invited_by, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
RETURNING id, email, token, status, invited_by, accepted_by, expires_at, created_at, accepted_at
`

type CreateInvitationParams struct {
	ID        int64              `json:"id"`
	Email     string             `json:"email"`
	Token     string             `json:"token"`
	Status    string             `json:"status"`
	InvitedBy *int64             `json:"invited_by"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.ID,
		arg.Email,
		arg.Token,
		arg.Status,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Token,
		&i.Status,
		&i.InvitedBy,
		&i.AcceptedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const expireOldInvitations = `-- name: ExpireOldInvitations :exec
UPDATE invitations 
SET status = 'expired'
WHERE status = 'pending' AND expires_at < now()
`

func (q *Queries) ExpireOldInvitations(ctx context.Context) error {
	_, err := q.db.Exec(ctx, expireOldInvitations)
	return err
}

const getInvitationByEmail = `-- name: GetInvitationByEmail :one
SELECT id, email, token, status, invited_by, accepted_by, expires_at, created_at, accepted_at FROM invitations 
WHERE email = $1 AND status = 'pending'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetInvitationByEmail(ctx context.Context, email string) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByEmail, email)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Token,
		&i.Status,
		&i.InvitedBy,
		&i.AcceptedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const getInvitationByID = `-- name: GetInvitationByID :one
SELECT id, email, token, status, invited_by, accepted_by, expires_at, created_at, accepted_at FROM invitations WHERE id = $1
`

func (q *Queries) GetInvitationByID(ctx context.Context, id int64) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByID, id)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Token,
		&i.Status,
		&i.InvitedBy,
		&i.AcceptedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const getInvitationByToken = `-- name: GetInvitationByToken :one
SELECT id, email, token, status, invited_by, accepted_by, expires_at, created_at, accepted_at FROM invitations WHERE token = $1
`

func (q *Queries) GetInvitationByToken(ctx context.Context, token string) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByToken, token)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Token,
		&i.Status,
		&i.InvitedBy,
		&i.AcceptedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const getValidInvitationByToken = `-- name: GetValidInvitationByToken :one
SELECT id, email, token, status, invited_by, accepted_by, expires_at, created_at, accepted_at FROM invitations 
WHERE token = $1 
  AND status = 'pending' 
  AND expires_at > now()
`

func (q *Queries) GetValidInvitationByToken(ctx context.Context, token string) (Invitation, error) {
	row := q.db.QueryRow(ctx, getValidInvitationByToken, token)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Token,
		&i.Status,
		&i.InvitedBy,
		&i.AcceptedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.AcceptedAt,
	)
	return i, err
}

const listInvitations = `-- name: ListInvitations :many
SELECT id, email, token, status, invited_by, accepted_by, expires_at, created_at, accepted_at FROM invitations 
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListInvitationsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListInvitations(ctx context.Context, arg ListInvitationsParams) ([]Invitation, error) {
	rows, err := q.db.Query(ctx, listInvitations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invitation
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Token,
			&i.Status,
			&i.InvitedBy,
			&i.AcceptedBy,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.AcceptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingInvitations = `-- name: ListPendingInvitations :many
SELECT id, email, token, status, invited_by, accepted_by, expires_at, created_at, accepted_at FROM invitations 
WHERE status = 'pending'
ORDER BY created_at DESC
`

func (q *Queries) ListPendingInvitations(ctx context.Context) ([]Invitation, error) {
	rows, err := q.db.Query(ctx, listPendingInvitations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invitation
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Token,
			&i.Status,
			&i.InvitedBy,
			&i.AcceptedBy,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.AcceptedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeInvitation = `-- name: RevokeInvitation :one
UPDATE invitations 
SET status = 'revoked'
WHERE id = $1 AND status = 'pending'
RETURNING id, email, token, status, invited_by, accepted_by, expires_at, created_at, accepted_at
`

func (q *Queries) RevokeInvitation(ctx context.Context, id int64) (Invitation, error) {
	row := q.db.QueryRow(ctx, revokeInvitation, id)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Token,
		&i.Status,
		&i.InvitedBy,
		&i.AcceptedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.AcceptedAt,
	)
	return i, err
}
