// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: learnings.sql

package sqlc

import (
	"context"
)

const createLearning = `-- name: CreateLearning :one
INSERT INTO learnings (
    id, workspace_id, rule_updated_by_issue_id, type, content
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, short_id, workspace_id, rule_updated_by_issue_id, type, content, created_at, updated_at
`

type CreateLearningParams struct {
	ID                   int64  `json:"id"`
	WorkspaceID          int64  `json:"workspace_id"`
	RuleUpdatedByIssueID *int64 `json:"rule_updated_by_issue_id"`
	Type                 string `json:"type"`
	Content              string `json:"content"`
}

func (q *Queries) CreateLearning(ctx context.Context, arg CreateLearningParams) (Learning, error) {
	row := q.db.QueryRow(ctx, createLearning,
		arg.ID,
		arg.WorkspaceID,
		arg.RuleUpdatedByIssueID,
		arg.Type,
		arg.Content,
	)
	var i Learning
	err := row.Scan(
		&i.ID,
		&i.ShortID,
		&i.WorkspaceID,
		&i.RuleUpdatedByIssueID,
		&i.Type,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLearning = `-- name: DeleteLearning :exec
DELETE FROM learnings WHERE id = $1
`

func (q *Queries) DeleteLearning(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteLearning, id)
	return err
}

const getLearning = `-- name: GetLearning :one
SELECT id, short_id, workspace_id, rule_updated_by_issue_id, type, content, created_at, updated_at FROM learnings
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetLearning(ctx context.Context, id int64) (Learning, error) {
	row := q.db.QueryRow(ctx, getLearning, id)
	var i Learning
	err := row.Scan(
		&i.ID,
		&i.ShortID,
		&i.WorkspaceID,
		&i.RuleUpdatedByIssueID,
		&i.Type,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLearningsByWorkspace = `-- name: ListLearningsByWorkspace :many
SELECT id, short_id, workspace_id, rule_updated_by_issue_id, type, content, created_at, updated_at FROM learnings
WHERE workspace_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListLearningsByWorkspace(ctx context.Context, workspaceID int64) ([]Learning, error) {
	rows, err := q.db.Query(ctx, listLearningsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Learning
	for rows.Next() {
		var i Learning
		if err := rows.Scan(
			&i.ID,
			&i.ShortID,
			&i.WorkspaceID,
			&i.RuleUpdatedByIssueID,
			&i.Type,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLearningsByWorkspaceAndType = `-- name: ListLearningsByWorkspaceAndType :many
SELECT id, short_id, workspace_id, rule_updated_by_issue_id, type, content, created_at, updated_at FROM learnings
WHERE workspace_id = $1 AND type = $2
ORDER BY created_at DESC
`

type ListLearningsByWorkspaceAndTypeParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	Type        string `json:"type"`
}

func (q *Queries) ListLearningsByWorkspaceAndType(ctx context.Context, arg ListLearningsByWorkspaceAndTypeParams) ([]Learning, error) {
	rows, err := q.db.Query(ctx, listLearningsByWorkspaceAndType, arg.WorkspaceID, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Learning
	for rows.Next() {
		var i Learning
		if err := rows.Scan(
			&i.ID,
			&i.ShortID,
			&i.WorkspaceID,
			&i.RuleUpdatedByIssueID,
			&i.Type,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLearning = `-- name: UpdateLearning :one
UPDATE learnings
SET content = $2, updated_at = now()
WHERE id = $1
RETURNING id, short_id, workspace_id, rule_updated_by_issue_id, type, content, created_at, updated_at
`

type UpdateLearningParams struct {
	ID      int64  `json:"id"`
	Content string `json:"content"`
}

func (q *Queries) UpdateLearning(ctx context.Context, arg UpdateLearningParams) (Learning, error) {
	row := q.db.QueryRow(ctx, updateLearning, arg.ID, arg.Content)
	var i Learning
	err := row.Scan(
		&i.ID,
		&i.ShortID,
		&i.WorkspaceID,
		&i.RuleUpdatedByIssueID,
		&i.Type,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
