// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type EventLog struct {
	ID              int64              `json:"id"`
	WorkspaceID     int64              `json:"workspace_id"`
	Source          string             `json:"source"`
	EventType       string             `json:"event_type"`
	Payload         *string            `json:"payload"`
	ExternalID      *string            `json:"external_id"`
	ProcessedAt     pgtype.Timestamptz `json:"processed_at"`
	ProcessingError *string            `json:"processing_error"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Integration struct {
	ID                  int64              `json:"id"`
	WorkspaceID         int64              `json:"workspace_id"`
	OrganizationID      int64              `json:"organization_id"`
	SetupByUserID       int64              `json:"setup_by_user_id"`
	Provider            string             `json:"provider"`
	Capabilities        []string           `json:"capabilities"`
	ProviderBaseUrl     *string            `json:"provider_base_url"`
	ExternalOrgID       *string            `json:"external_org_id"`
	ExternalWorkspaceID *string            `json:"external_workspace_id"`
	IsEnabled           bool               `json:"is_enabled"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type IntegrationConfig struct {
	ID            int64              `json:"id"`
	IntegrationID int64              `json:"integration_id"`
	Key           string             `json:"key"`
	Value         json.RawMessage    `json:"value"`
	ConfigType    string             `json:"config_type"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type IntegrationCredential struct {
	ID             int64              `json:"id"`
	IntegrationID  int64              `json:"integration_id"`
	UserID         *int64             `json:"user_id"`
	CredentialType string             `json:"credential_type"`
	AccessToken    string             `json:"access_token"`
	RefreshToken   *string            `json:"refresh_token"`
	TokenExpiresAt pgtype.Timestamptz `json:"token_expires_at"`
	Scopes         []string           `json:"scopes"`
	IsPrimary      bool               `json:"is_primary"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	RevokedAt      pgtype.Timestamptz `json:"revoked_at"`
}

type Organization struct {
	ID          int64              `json:"id"`
	AdminUserID int64              `json:"admin_user_id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	IsDeleted   bool               `json:"is_deleted"`
}

type Repository struct {
	ID             int64              `json:"id"`
	WorkspaceID    int64              `json:"workspace_id"`
	IntegrationID  int64              `json:"integration_id"`
	Name           string             `json:"name"`
	Slug           string             `json:"slug"`
	Url            string             `json:"url"`
	Description    *string            `json:"description"`
	ExternalRepoID string             `json:"external_repo_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type User struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Email     string             `json:"email"`
	AvatarUrl *string            `json:"avatar_url"`
	WorkosID  *string            `json:"workos_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Workspace struct {
	ID             int64              `json:"id"`
	AdminUserID    int64              `json:"admin_user_id"`
	OrganizationID int64              `json:"organization_id"`
	UserID         int64              `json:"user_id"`
	Name           string             `json:"name"`
	Slug           string             `json:"slug"`
	Description    *string            `json:"description"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	IsDeleted      bool               `json:"is_deleted"`
}
