// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EventLog struct {
	ID                  int64              `json:"id"`
	WorkspaceID         int64              `json:"workspace_id"`
	IssueID             int64              `json:"issue_id"`
	TriggeredByUsername string             `json:"triggered_by_username"`
	Source              string             `json:"source"`
	EventType           string             `json:"event_type"`
	Payload             []byte             `json:"payload"`
	ExternalID          *string            `json:"external_id"`
	DedupeKey           string             `json:"dedupe_key"`
	ProcessedAt         pgtype.Timestamptz `json:"processed_at"`
	ProcessingError     *string            `json:"processing_error"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type Gap struct {
	ID      int64 `json:"id"`
	IssueID int64 `json:"issue_id"`
	// open | resolved | skipped
	Status   string  `json:"status"`
	Question string  `json:"question"`
	Evidence *string `json:"evidence"`
	// blocking | high | medium | low
	Severity string `json:"severity"`
	// reporter | assignee
	Respondent string             `json:"respondent"`
	LearningID *int64             `json:"learning_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
}

type Integration struct {
	ID                  int64              `json:"id"`
	WorkspaceID         int64              `json:"workspace_id"`
	OrganizationID      int64              `json:"organization_id"`
	SetupByUserID       int64              `json:"setup_by_user_id"`
	Provider            string             `json:"provider"`
	Capabilities        []string           `json:"capabilities"`
	ProviderBaseUrl     *string            `json:"provider_base_url"`
	ExternalOrgID       *string            `json:"external_org_id"`
	ExternalWorkspaceID *string            `json:"external_workspace_id"`
	IsEnabled           bool               `json:"is_enabled"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type IntegrationConfig struct {
	ID            int64              `json:"id"`
	IntegrationID int64              `json:"integration_id"`
	Key           string             `json:"key"`
	Value         []byte             `json:"value"`
	ConfigType    string             `json:"config_type"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type IntegrationCredential struct {
	ID             int64              `json:"id"`
	IntegrationID  int64              `json:"integration_id"`
	UserID         *int64             `json:"user_id"`
	CredentialType string             `json:"credential_type"`
	AccessToken    string             `json:"access_token"`
	RefreshToken   *string            `json:"refresh_token"`
	TokenExpiresAt pgtype.Timestamptz `json:"token_expires_at"`
	Scopes         []string           `json:"scopes"`
	IsPrimary      bool               `json:"is_primary"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	RevokedAt      pgtype.Timestamptz `json:"revoked_at"`
}

type Issue struct {
	ID               int64    `json:"id"`
	IntegrationID    int64    `json:"integration_id"`
	ExternalIssueID  string   `json:"external_issue_id"`
	Provider         string   `json:"provider"`
	Title            *string  `json:"title"`
	Description      *string  `json:"description"`
	Labels           []string `json:"labels"`
	Members          []string `json:"members"`
	Assignees        []string `json:"assignees"`
	Reporter         *string  `json:"reporter"`
	ExternalIssueUrl *string  `json:"external_issue_url"`
	Keywords         []byte   `json:"keywords"`
	CodeFindings     []byte   `json:"code_findings"`
	Learnings        []byte   `json:"learnings"`
	Discussions      []byte   `json:"discussions"`
	Spec             *string  `json:"spec"`
	// idle | queued | processing
	ProcessingStatus    string             `json:"processing_status"`
	ProcessingStartedAt pgtype.Timestamptz `json:"processing_started_at"`
	LastProcessedAt     pgtype.Timestamptz `json:"last_processed_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type Learning struct {
	ID                   int64              `json:"id"`
	WorkspaceID          int64              `json:"workspace_id"`
	RuleUpdatedByIssueID *int64             `json:"rule_updated_by_issue_id"`
	Type                 string             `json:"type"`
	Content              string             `json:"content"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type LlmEval struct {
	ID               int64              `json:"id"`
	WorkspaceID      *int64             `json:"workspace_id"`
	IssueID          *int64             `json:"issue_id"`
	Stage            string             `json:"stage"`
	InputText        string             `json:"input_text"`
	OutputJson       []byte             `json:"output_json"`
	Model            string             `json:"model"`
	Temperature      *float64           `json:"temperature"`
	PromptVersion    *string            `json:"prompt_version"`
	LatencyMs        *int32             `json:"latency_ms"`
	PromptTokens     *int32             `json:"prompt_tokens"`
	CompletionTokens *int32             `json:"completion_tokens"`
	Rating           *int32             `json:"rating"`
	RatingNotes      *string            `json:"rating_notes"`
	RatedByUserID    *int64             `json:"rated_by_user_id"`
	RatedAt          pgtype.Timestamptz `json:"rated_at"`
	ExpectedJson     []byte             `json:"expected_json"`
	EvalScore        *float64           `json:"eval_score"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Organization struct {
	ID          int64              `json:"id"`
	AdminUserID int64              `json:"admin_user_id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	IsDeleted   bool               `json:"is_deleted"`
}

type Repository struct {
	ID             int64              `json:"id"`
	WorkspaceID    int64              `json:"workspace_id"`
	IntegrationID  int64              `json:"integration_id"`
	Name           string             `json:"name"`
	Slug           string             `json:"slug"`
	Url            string             `json:"url"`
	Description    *string            `json:"description"`
	ExternalRepoID string             `json:"external_repo_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type User struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Email     string             `json:"email"`
	AvatarUrl *string            `json:"avatar_url"`
	WorkosID  *string            `json:"workos_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Workspace struct {
	ID             int64              `json:"id"`
	AdminUserID    int64              `json:"admin_user_id"`
	OrganizationID int64              `json:"organization_id"`
	UserID         int64              `json:"user_id"`
	Name           string             `json:"name"`
	Slug           string             `json:"slug"`
	Description    *string            `json:"description"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	IsDeleted      bool               `json:"is_deleted"`
}
