// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organizations.sql

package sqlc

import (
	"context"
)

const createOrganization = `-- name: CreateOrganization :one
INSERT INTO organizations (id, admin_user_id, name, slug, created_at, updated_at)
VALUES ($1, $2, $3, $4, now(), now())
RETURNING id, admin_user_id, name, slug, created_at, updated_at, is_deleted
`

type CreateOrganizationParams struct {
	ID          int64  `json:"id"`
	AdminUserID int64  `json:"admin_user_id"`
	Name        string `json:"name"`
	Slug        string `json:"slug"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, createOrganization,
		arg.ID,
		arg.AdminUserID,
		arg.Name,
		arg.Slug,
	)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.AdminUserID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const getOrganization = `-- name: GetOrganization :one
SELECT id, admin_user_id, name, slug, created_at, updated_at, is_deleted FROM organizations WHERE id = $1 AND is_deleted = false
`

func (q *Queries) GetOrganization(ctx context.Context, id int64) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganization, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.AdminUserID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const getOrganizationBySlug = `-- name: GetOrganizationBySlug :one
SELECT id, admin_user_id, name, slug, created_at, updated_at, is_deleted FROM organizations WHERE slug = $1 AND is_deleted = false
`

func (q *Queries) GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationBySlug, slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.AdminUserID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const listOrganizationsByAdmin = `-- name: ListOrganizationsByAdmin :many
SELECT id, admin_user_id, name, slug, created_at, updated_at, is_deleted FROM organizations 
WHERE admin_user_id = $1 AND is_deleted = false
ORDER BY created_at DESC
`

func (q *Queries) ListOrganizationsByAdmin(ctx context.Context, adminUserID int64) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listOrganizationsByAdmin, adminUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.AdminUserID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteOrganization = `-- name: SoftDeleteOrganization :exec
UPDATE organizations SET is_deleted = true, updated_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteOrganization(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteOrganization, id)
	return err
}

const updateOrganization = `-- name: UpdateOrganization :one
UPDATE organizations
SET name = $2, slug = $3, updated_at = now()
WHERE id = $1 AND is_deleted = false
RETURNING id, admin_user_id, name, slug, created_at, updated_at, is_deleted
`

type UpdateOrganizationParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
	Slug string `json:"slug"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) (Organization, error) {
	row := q.db.QueryRow(ctx, updateOrganization, arg.ID, arg.Name, arg.Slug)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.AdminUserID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}
