// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pipeline_runs.sql

package sqlc

import (
	"context"
)

const createPipelineRun = `-- name: CreatePipelineRun :one
INSERT INTO pipeline_runs (id, event_log_id, attempt, status, error, started_at)
VALUES ($1, $2, $3, $4, $5, now())
RETURNING id, event_log_id, attempt, status, error, started_at, finished_at
`

type CreatePipelineRunParams struct {
	ID         int64   `json:"id"`
	EventLogID int64   `json:"event_log_id"`
	Attempt    int32   `json:"attempt"`
	Status     string  `json:"status"`
	Error      *string `json:"error"`
}

func (q *Queries) CreatePipelineRun(ctx context.Context, arg CreatePipelineRunParams) (PipelineRun, error) {
	row := q.db.QueryRow(ctx, createPipelineRun,
		arg.ID,
		arg.EventLogID,
		arg.Attempt,
		arg.Status,
		arg.Error,
	)
	var i PipelineRun
	err := row.Scan(
		&i.ID,
		&i.EventLogID,
		&i.Attempt,
		&i.Status,
		&i.Error,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const finishPipelineRun = `-- name: FinishPipelineRun :exec
UPDATE pipeline_runs
SET status = $2, error = $3, finished_at = now()
WHERE id = $1
`

type FinishPipelineRunParams struct {
	ID     int64   `json:"id"`
	Status string  `json:"status"`
	Error  *string `json:"error"`
}

func (q *Queries) FinishPipelineRun(ctx context.Context, arg FinishPipelineRunParams) error {
	_, err := q.db.Exec(ctx, finishPipelineRun, arg.ID, arg.Status, arg.Error)
	return err
}

const listPipelineRunsForEvent = `-- name: ListPipelineRunsForEvent :many
SELECT id, event_log_id, attempt, status, error, started_at, finished_at FROM pipeline_runs
WHERE event_log_id = $1
ORDER BY started_at DESC
LIMIT $2
`

type ListPipelineRunsForEventParams struct {
	EventLogID int64 `json:"event_log_id"`
	Limit      int32 `json:"limit"`
}

func (q *Queries) ListPipelineRunsForEvent(ctx context.Context, arg ListPipelineRunsForEventParams) ([]PipelineRun, error) {
	rows, err := q.db.Query(ctx, listPipelineRunsForEvent, arg.EventLogID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PipelineRun
	for rows.Next() {
		var i PipelineRun
		if err := rows.Scan(
			&i.ID,
			&i.EventLogID,
			&i.Attempt,
			&i.Status,
			&i.Error,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
