// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repositories.sql

package sqlc

import (
	"context"
)

const createRepository = `-- name: CreateRepository :one
INSERT INTO repositories (
    id, workspace_id, integration_id,
    name, slug, url, description, external_repo_id,
    is_enabled, default_branch,
    created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, now(), now())
RETURNING id, workspace_id, integration_id, name, slug, url, description, is_enabled, default_branch, external_repo_id, created_at, updated_at
`

type CreateRepositoryParams struct {
	ID             int64   `json:"id"`
	WorkspaceID    int64   `json:"workspace_id"`
	IntegrationID  int64   `json:"integration_id"`
	Name           string  `json:"name"`
	Slug           string  `json:"slug"`
	Url            string  `json:"url"`
	Description    *string `json:"description"`
	ExternalRepoID string  `json:"external_repo_id"`
	IsEnabled      bool    `json:"is_enabled"`
	DefaultBranch  *string `json:"default_branch"`
}

func (q *Queries) CreateRepository(ctx context.Context, arg CreateRepositoryParams) (Repository, error) {
	row := q.db.QueryRow(ctx, createRepository,
		arg.ID,
		arg.WorkspaceID,
		arg.IntegrationID,
		arg.Name,
		arg.Slug,
		arg.Url,
		arg.Description,
		arg.ExternalRepoID,
		arg.IsEnabled,
		arg.DefaultBranch,
	)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.IntegrationID,
		&i.Name,
		&i.Slug,
		&i.Url,
		&i.Description,
		&i.IsEnabled,
		&i.DefaultBranch,
		&i.ExternalRepoID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRepositoriesByIntegration = `-- name: DeleteRepositoriesByIntegration :exec
DELETE FROM repositories WHERE integration_id = $1
`

func (q *Queries) DeleteRepositoriesByIntegration(ctx context.Context, integrationID int64) error {
	_, err := q.db.Exec(ctx, deleteRepositoriesByIntegration, integrationID)
	return err
}

const deleteRepository = `-- name: DeleteRepository :exec
DELETE FROM repositories WHERE id = $1
`

func (q *Queries) DeleteRepository(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteRepository, id)
	return err
}

const getRepository = `-- name: GetRepository :one
SELECT id, workspace_id, integration_id, name, slug, url, description, is_enabled, default_branch, external_repo_id, created_at, updated_at FROM repositories WHERE id = $1
`

func (q *Queries) GetRepository(ctx context.Context, id int64) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepository, id)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.IntegrationID,
		&i.Name,
		&i.Slug,
		&i.Url,
		&i.Description,
		&i.IsEnabled,
		&i.DefaultBranch,
		&i.ExternalRepoID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepositoryByExternalID = `-- name: GetRepositoryByExternalID :one
SELECT id, workspace_id, integration_id, name, slug, url, description, is_enabled, default_branch, external_repo_id, created_at, updated_at FROM repositories 
WHERE integration_id = $1 AND external_repo_id = $2
`

type GetRepositoryByExternalIDParams struct {
	IntegrationID  int64  `json:"integration_id"`
	ExternalRepoID string `json:"external_repo_id"`
}

func (q *Queries) GetRepositoryByExternalID(ctx context.Context, arg GetRepositoryByExternalIDParams) (Repository, error) {
	row := q.db.QueryRow(ctx, getRepositoryByExternalID, arg.IntegrationID, arg.ExternalRepoID)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.IntegrationID,
		&i.Name,
		&i.Slug,
		&i.Url,
		&i.Description,
		&i.IsEnabled,
		&i.DefaultBranch,
		&i.ExternalRepoID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledRepositoriesByIntegration = `-- name: ListEnabledRepositoriesByIntegration :many
SELECT id, workspace_id, integration_id, name, slug, url, description, is_enabled, default_branch, external_repo_id, created_at, updated_at FROM repositories
WHERE integration_id = $1 AND is_enabled = true
ORDER BY name ASC
`

func (q *Queries) ListEnabledRepositoriesByIntegration(ctx context.Context, integrationID int64) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listEnabledRepositoriesByIntegration, integrationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repository
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.IntegrationID,
			&i.Name,
			&i.Slug,
			&i.Url,
			&i.Description,
			&i.IsEnabled,
			&i.DefaultBranch,
			&i.ExternalRepoID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledRepositoriesByWorkspace = `-- name: ListEnabledRepositoriesByWorkspace :many
SELECT id, workspace_id, integration_id, name, slug, url, description, is_enabled, default_branch, external_repo_id, created_at, updated_at FROM repositories
WHERE workspace_id = $1 AND is_enabled = true
ORDER BY name ASC
`

func (q *Queries) ListEnabledRepositoriesByWorkspace(ctx context.Context, workspaceID int64) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listEnabledRepositoriesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repository
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.IntegrationID,
			&i.Name,
			&i.Slug,
			&i.Url,
			&i.Description,
			&i.IsEnabled,
			&i.DefaultBranch,
			&i.ExternalRepoID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepositoriesByIntegration = `-- name: ListRepositoriesByIntegration :many
SELECT id, workspace_id, integration_id, name, slug, url, description, is_enabled, default_branch, external_repo_id, created_at, updated_at FROM repositories 
WHERE integration_id = $1
ORDER BY name ASC
`

func (q *Queries) ListRepositoriesByIntegration(ctx context.Context, integrationID int64) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listRepositoriesByIntegration, integrationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repository
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.IntegrationID,
			&i.Name,
			&i.Slug,
			&i.Url,
			&i.Description,
			&i.IsEnabled,
			&i.DefaultBranch,
			&i.ExternalRepoID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepositoriesByWorkspace = `-- name: ListRepositoriesByWorkspace :many
SELECT id, workspace_id, integration_id, name, slug, url, description, is_enabled, default_branch, external_repo_id, created_at, updated_at FROM repositories 
WHERE workspace_id = $1
ORDER BY name ASC
`

func (q *Queries) ListRepositoriesByWorkspace(ctx context.Context, workspaceID int64) ([]Repository, error) {
	rows, err := q.db.Query(ctx, listRepositoriesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repository
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.IntegrationID,
			&i.Name,
			&i.Slug,
			&i.Url,
			&i.Description,
			&i.IsEnabled,
			&i.DefaultBranch,
			&i.ExternalRepoID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRepositoryEnabled = `-- name: SetRepositoryEnabled :one
UPDATE repositories
SET is_enabled = $2, updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, integration_id, name, slug, url, description, is_enabled, default_branch, external_repo_id, created_at, updated_at
`

type SetRepositoryEnabledParams struct {
	ID        int64 `json:"id"`
	IsEnabled bool  `json:"is_enabled"`
}

func (q *Queries) SetRepositoryEnabled(ctx context.Context, arg SetRepositoryEnabledParams) (Repository, error) {
	row := q.db.QueryRow(ctx, setRepositoryEnabled, arg.ID, arg.IsEnabled)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.IntegrationID,
		&i.Name,
		&i.Slug,
		&i.Url,
		&i.Description,
		&i.IsEnabled,
		&i.DefaultBranch,
		&i.ExternalRepoID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRepository = `-- name: UpdateRepository :one
UPDATE repositories
SET name = $2, slug = $3, url = $4, description = $5, updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, integration_id, name, slug, url, description, is_enabled, default_branch, external_repo_id, created_at, updated_at
`

type UpdateRepositoryParams struct {
	ID          int64   `json:"id"`
	Name        string  `json:"name"`
	Slug        string  `json:"slug"`
	Url         string  `json:"url"`
	Description *string `json:"description"`
}

func (q *Queries) UpdateRepository(ctx context.Context, arg UpdateRepositoryParams) (Repository, error) {
	row := q.db.QueryRow(ctx, updateRepository,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Url,
		arg.Description,
	)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.IntegrationID,
		&i.Name,
		&i.Slug,
		&i.Url,
		&i.Description,
		&i.IsEnabled,
		&i.DefaultBranch,
		&i.ExternalRepoID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRepositoryDefaultBranch = `-- name: UpdateRepositoryDefaultBranch :one
UPDATE repositories
SET default_branch = $2, updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, integration_id, name, slug, url, description, is_enabled, default_branch, external_repo_id, created_at, updated_at
`

type UpdateRepositoryDefaultBranchParams struct {
	ID            int64   `json:"id"`
	DefaultBranch *string `json:"default_branch"`
}

func (q *Queries) UpdateRepositoryDefaultBranch(ctx context.Context, arg UpdateRepositoryDefaultBranchParams) (Repository, error) {
	row := q.db.QueryRow(ctx, updateRepositoryDefaultBranch, arg.ID, arg.DefaultBranch)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.IntegrationID,
		&i.Name,
		&i.Slug,
		&i.Url,
		&i.Description,
		&i.IsEnabled,
		&i.DefaultBranch,
		&i.ExternalRepoID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
