// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, name, email, avatar_url, workos_id, created_at, updated_at)
VALUES ($1, $2, LOWER($3), $4, $5, now(), now())
RETURNING id, name, email, avatar_url, workos_id, created_at, updated_at
`

type CreateUserParams struct {
	ID        int64   `json:"id"`
	Name      string  `json:"name"`
	Email     string  `json:"email"`
	AvatarUrl *string `json:"avatar_url"`
	WorkosID  *string `json:"workos_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.AvatarUrl,
		arg.WorkosID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.AvatarUrl,
		&i.WorkosID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, name, email, avatar_url, workos_id, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.AvatarUrl,
		&i.WorkosID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, avatar_url, workos_id, created_at, updated_at FROM users WHERE LOWER(email) = LOWER($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.AvatarUrl,
		&i.WorkosID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByWorkOSID = `-- name: GetUserByWorkOSID :one
SELECT id, name, email, avatar_url, workos_id, created_at, updated_at FROM users WHERE workos_id = $1
`

func (q *Queries) GetUserByWorkOSID(ctx context.Context, workosID *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByWorkOSID, workosID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.AvatarUrl,
		&i.WorkosID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET name = $1, email = LOWER($2), avatar_url = $3, workos_id = $4, updated_at = now()
WHERE id = $5
RETURNING id, name, email, avatar_url, workos_id, created_at, updated_at
`

type UpdateUserParams struct {
	Name      string  `json:"name"`
	Email     string  `json:"email"`
	AvatarUrl *string `json:"avatar_url"`
	WorkosID  *string `json:"workos_id"`
	ID        int64   `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Name,
		arg.Email,
		arg.AvatarUrl,
		arg.WorkosID,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.AvatarUrl,
		&i.WorkosID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (id, name, email, avatar_url, workos_id, created_at, updated_at)
VALUES ($1, $2, LOWER($3), $4, $5, now(), now())
ON CONFLICT (email) DO UPDATE SET
  name = EXCLUDED.name,
  avatar_url = EXCLUDED.avatar_url,
  workos_id = EXCLUDED.workos_id,
  updated_at = now()
RETURNING id, name, email, avatar_url, workos_id, created_at, updated_at
`

type UpsertUserParams struct {
	ID        int64   `json:"id"`
	Name      string  `json:"name"`
	Email     string  `json:"email"`
	AvatarUrl *string `json:"avatar_url"`
	WorkosID  *string `json:"workos_id"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.AvatarUrl,
		arg.WorkosID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.AvatarUrl,
		&i.WorkosID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserByWorkOSID = `-- name: UpsertUserByWorkOSID :one
INSERT INTO users (id, name, email, avatar_url, workos_id, created_at, updated_at)
VALUES ($1, $2, LOWER($3), $4, $5, now(), now())
ON CONFLICT (workos_id) DO UPDATE SET
  name = EXCLUDED.name,
  email = LOWER(EXCLUDED.email),
  avatar_url = EXCLUDED.avatar_url,
  updated_at = now()
RETURNING id, name, email, avatar_url, workos_id, created_at, updated_at
`

type UpsertUserByWorkOSIDParams struct {
	ID        int64   `json:"id"`
	Name      string  `json:"name"`
	Email     string  `json:"email"`
	AvatarUrl *string `json:"avatar_url"`
	WorkosID  *string `json:"workos_id"`
}

func (q *Queries) UpsertUserByWorkOSID(ctx context.Context, arg UpsertUserByWorkOSIDParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUserByWorkOSID,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.AvatarUrl,
		arg.WorkosID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.AvatarUrl,
		&i.WorkosID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
