// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspaces.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (
    id, admin_user_id, organization_id, user_id, 
    name, slug, description, created_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, now(), now())
RETURNING id, admin_user_id, organization_id, user_id, name, slug, description, repo_ready_at, created_at, updated_at, is_deleted
`

type CreateWorkspaceParams struct {
	ID             int64   `json:"id"`
	AdminUserID    int64   `json:"admin_user_id"`
	OrganizationID int64   `json:"organization_id"`
	UserID         int64   `json:"user_id"`
	Name           string  `json:"name"`
	Slug           string  `json:"slug"`
	Description    *string `json:"description"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace,
		arg.ID,
		arg.AdminUserID,
		arg.OrganizationID,
		arg.UserID,
		arg.Name,
		arg.Slug,
		arg.Description,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.AdminUserID,
		&i.OrganizationID,
		&i.UserID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.RepoReadyAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, admin_user_id, organization_id, user_id, name, slug, description, repo_ready_at, created_at, updated_at, is_deleted FROM workspaces WHERE id = $1 AND is_deleted = false
`

func (q *Queries) GetWorkspace(ctx context.Context, id int64) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.AdminUserID,
		&i.OrganizationID,
		&i.UserID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.RepoReadyAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const getWorkspaceByOrgAndSlug = `-- name: GetWorkspaceByOrgAndSlug :one
SELECT id, admin_user_id, organization_id, user_id, name, slug, description, repo_ready_at, created_at, updated_at, is_deleted FROM workspaces 
WHERE organization_id = $1 AND slug = $2 AND is_deleted = false
`

type GetWorkspaceByOrgAndSlugParams struct {
	OrganizationID int64  `json:"organization_id"`
	Slug           string `json:"slug"`
}

func (q *Queries) GetWorkspaceByOrgAndSlug(ctx context.Context, arg GetWorkspaceByOrgAndSlugParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByOrgAndSlug, arg.OrganizationID, arg.Slug)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.AdminUserID,
		&i.OrganizationID,
		&i.UserID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.RepoReadyAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const listWorkspacesByOrganization = `-- name: ListWorkspacesByOrganization :many
SELECT id, admin_user_id, organization_id, user_id, name, slug, description, repo_ready_at, created_at, updated_at, is_deleted FROM workspaces 
WHERE organization_id = $1 AND is_deleted = false
ORDER BY created_at DESC
`

func (q *Queries) ListWorkspacesByOrganization(ctx context.Context, organizationID int64) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listWorkspacesByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.AdminUserID,
			&i.OrganizationID,
			&i.UserID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.RepoReadyAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesByUser = `-- name: ListWorkspacesByUser :many
SELECT id, admin_user_id, organization_id, user_id, name, slug, description, repo_ready_at, created_at, updated_at, is_deleted FROM workspaces 
WHERE user_id = $1 AND is_deleted = false
ORDER BY created_at DESC
`

func (q *Queries) ListWorkspacesByUser(ctx context.Context, userID int64) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listWorkspacesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.AdminUserID,
			&i.OrganizationID,
			&i.UserID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.RepoReadyAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsDeleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setWorkspaceRepoReadyAt = `-- name: SetWorkspaceRepoReadyAt :one
UPDATE workspaces
SET repo_ready_at = $2, updated_at = now()
WHERE id = $1 AND is_deleted = false
RETURNING id, admin_user_id, organization_id, user_id, name, slug, description, repo_ready_at, created_at, updated_at, is_deleted
`

type SetWorkspaceRepoReadyAtParams struct {
	ID          int64              `json:"id"`
	RepoReadyAt pgtype.Timestamptz `json:"repo_ready_at"`
}

func (q *Queries) SetWorkspaceRepoReadyAt(ctx context.Context, arg SetWorkspaceRepoReadyAtParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, setWorkspaceRepoReadyAt, arg.ID, arg.RepoReadyAt)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.AdminUserID,
		&i.OrganizationID,
		&i.UserID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.RepoReadyAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}

const softDeleteWorkspace = `-- name: SoftDeleteWorkspace :exec
UPDATE workspaces SET is_deleted = true, updated_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteWorkspace(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteWorkspace, id)
	return err
}

const updateWorkspace = `-- name: UpdateWorkspace :one
UPDATE workspaces
SET name = $2, slug = $3, description = $4, updated_at = now()
WHERE id = $1 AND is_deleted = false
RETURNING id, admin_user_id, organization_id, user_id, name, slug, description, repo_ready_at, created_at, updated_at, is_deleted
`

type UpdateWorkspaceParams struct {
	ID          int64   `json:"id"`
	Name        string  `json:"name"`
	Slug        string  `json:"slug"`
	Description *string `json:"description"`
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspace,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Description,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.AdminUserID,
		&i.OrganizationID,
		&i.UserID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.RepoReadyAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
	)
	return i, err
}
