// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_event_logs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkspaceEventLog = `-- name: CreateWorkspaceEventLog :one
INSERT INTO workspace_event_logs (
    id, workspace_id, organization_id, repo_id,
    event_type, status, error, metadata
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, workspace_id, organization_id, repo_id, event_type, status, error, metadata, started_at, finished_at, created_at, updated_at
`

type CreateWorkspaceEventLogParams struct {
	ID             int64   `json:"id"`
	WorkspaceID    int64   `json:"workspace_id"`
	OrganizationID int64   `json:"organization_id"`
	RepoID         *int64  `json:"repo_id"`
	EventType      string  `json:"event_type"`
	Status         string  `json:"status"`
	Error          *string `json:"error"`
	Metadata       []byte  `json:"metadata"`
}

func (q *Queries) CreateWorkspaceEventLog(ctx context.Context, arg CreateWorkspaceEventLogParams) (WorkspaceEventLog, error) {
	row := q.db.QueryRow(ctx, createWorkspaceEventLog,
		arg.ID,
		arg.WorkspaceID,
		arg.OrganizationID,
		arg.RepoID,
		arg.EventType,
		arg.Status,
		arg.Error,
		arg.Metadata,
	)
	var i WorkspaceEventLog
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.OrganizationID,
		&i.RepoID,
		&i.EventType,
		&i.Status,
		&i.Error,
		&i.Metadata,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceEventLog = `-- name: GetWorkspaceEventLog :one
SELECT id, workspace_id, organization_id, repo_id, event_type, status, error, metadata, started_at, finished_at, created_at, updated_at FROM workspace_event_logs WHERE id = $1
`

func (q *Queries) GetWorkspaceEventLog(ctx context.Context, id int64) (WorkspaceEventLog, error) {
	row := q.db.QueryRow(ctx, getWorkspaceEventLog, id)
	var i WorkspaceEventLog
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.OrganizationID,
		&i.RepoID,
		&i.EventType,
		&i.Status,
		&i.Error,
		&i.Metadata,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkspaceEventLogsByWorkspace = `-- name: ListWorkspaceEventLogsByWorkspace :many
SELECT id, workspace_id, organization_id, repo_id, event_type, status, error, metadata, started_at, finished_at, created_at, updated_at FROM workspace_event_logs
WHERE workspace_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListWorkspaceEventLogsByWorkspaceParams struct {
	WorkspaceID int64 `json:"workspace_id"`
	Limit       int32 `json:"limit"`
}

func (q *Queries) ListWorkspaceEventLogsByWorkspace(ctx context.Context, arg ListWorkspaceEventLogsByWorkspaceParams) ([]WorkspaceEventLog, error) {
	rows, err := q.db.Query(ctx, listWorkspaceEventLogsByWorkspace, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspaceEventLog
	for rows.Next() {
		var i WorkspaceEventLog
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.OrganizationID,
			&i.RepoID,
			&i.EventType,
			&i.Status,
			&i.Error,
			&i.Metadata,
			&i.StartedAt,
			&i.FinishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkspaceEventLog = `-- name: UpdateWorkspaceEventLog :one
UPDATE workspace_event_logs
SET status = $2,
    error = $3,
    metadata = $4,
    started_at = COALESCE($5, started_at),
    finished_at = COALESCE($6, finished_at),
    updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, organization_id, repo_id, event_type, status, error, metadata, started_at, finished_at, created_at, updated_at
`

type UpdateWorkspaceEventLogParams struct {
	ID         int64              `json:"id"`
	Status     string             `json:"status"`
	Error      *string            `json:"error"`
	Metadata   []byte             `json:"metadata"`
	StartedAt  pgtype.Timestamptz `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) UpdateWorkspaceEventLog(ctx context.Context, arg UpdateWorkspaceEventLogParams) (WorkspaceEventLog, error) {
	row := q.db.QueryRow(ctx, updateWorkspaceEventLog,
		arg.ID,
		arg.Status,
		arg.Error,
		arg.Metadata,
		arg.StartedAt,
		arg.FinishedAt,
	)
	var i WorkspaceEventLog
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.OrganizationID,
		&i.RepoID,
		&i.EventType,
		&i.Status,
		&i.Error,
		&i.Metadata,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
