run:
  timeout: 5m
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - gofmt
    - gosec
    - misspell
    - unconvert
    - unparam
    - errorlint
    - errname
    - gocyclo
    - revive
    - testifylint
    - usetesting

  disable:
    - cyclop
    - exhaustive
    - gocognit
    - exhaustruct
    - forbidigo
    - funlen
    - gochecknoglobals
    - godox
    - nestif
    - nlreturn
    - varnamelen
    - wsl

  exclusions:
    paths:
      - vendor/.*
      - ".*\\.pb\\.go$"
      - core/db/sqlc/.*
      - tools/linters/.*

linters-settings:
  # Custom analyzers (temporarily disabled due to plugin compatibility)
  # Note: Go plugins require exact version matching with golangci-lint
  # Alternative: Run custom analyzer separately via 'make lint-custom'
  # custom:
  #   enumvalidator:
  #     path: ./tools/linters/plugin/enumvalidator.so
  #     description: Validates enum field assignments use constants not literals
  #     original-url: basegraph.app/relay/tools/linters/enumvalidator

  errcheck:
    check-type-assertions: true
    check-blank: false

  govet:
    enable-all: true
    disable:
      - shadow

  staticcheck:
    checks:
      - all

  gosec:
    excludes:
      - G404

  revive:
    rules:
      - name: exported
        disabled: true
      - name: package-comments
        disabled: true

  gocyclo:
    min-complexity: 100

  misspell:
    locale: US

  testifylint:
    enable-all: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - gocyclo

    - path: mocks_test\.go
      linters:
        - revive
        - stylecheck

  max-same-issues: 50
  max-issues-per-linter: 0
  new: false
